Transform: AWS::Serverless-2016-10-31
Description: Q1
Parameters:
  Environment:
    Type: String
Resources:
  PythonModuleLayers:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
      - python3.9
      ContentUri: s3://internal-projects-assets/generate-report-for-last-7days/58bb8a2838808701bac8087d95a1e726
      Description: python-module-layers
      LayerName:
        Fn::Sub: python-module-layers-${Environment}
      RetentionPolicy: Delete
    Metadata:
      SamResourceId: PythonModuleLayers
  OutputS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: cost-explorer-report-bucket-${Environment}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      Tags:
      - Key: Environment
        Value:
          Ref: Environment
    Metadata:
      SamResourceId: OutputS3Bucket
  GenerateReportFor7Days:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-west-2.amazonaws.com/internal-projects-assets/generate-report-for-last-7days/fe6b9fdd51d7257a2c6c33b5f67945ce.template
      Parameters:
        PythonModuleLayers:
          Ref: PythonModuleLayers
        Environment:
          Ref: Environment
        OutputS3Bucket:
          Ref: OutputS3Bucket
    Metadata:
      SamResourceId: GenerateReportFor7Days
