Transform: AWS::Serverless-2016-10-31
Description: Astuto Q1

Parameters:
  Environment:
    Type: String
  PythonModuleLayers:
    Type: String
    Description: PythonModuleLayers
  OutputS3Bucket:
    Type: String
    Description: OUTPUT_BUCKET

Resources:
  GenerateReportForLast7Days:
    Type: AWS::Serverless::Function
    Properties:
      Description: 'Python script that will eventually run in a CRON job every day at 9 AM, and computes cost report for last 7 days. Given that bill gets generated a bit late, if the report is run today, the cost will be calculated end day before yesterday'
      FunctionName: !Sub 'generate-report-for-last-7days-${Environment}'
      Runtime: python3.9
      Handler: app.handler
      CodeUri: ./src
      MemorySize: 256
      Timeout: 180
      Layers:
        - !Ref PythonModuleLayers
      Environment:
        Variables:
          Environment: !Ref Environment
          LOGGING_LEVEL: INFO
          OUTPUT_BUCKET: !Ref OutputS3Bucket
      Events:
        Generate7DaysReport:
          Type: ScheduleV2
          Properties:
              Description: 'Generate7DaysReport at 9am'
              Name: 'Generate7DaysReport'
              ScheduleExpression: cron(0 9 * * ? *)
              State: ENABLED
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref OutputS3Bucket
        - CostExplorerReadOnlyPolicy: {}
      Tags:
        Environment: !Ref Environment
